name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.3.0
      - run: mkdir -p build/android
      - run: godot --headless --export-release "Android" build/android/Odogwu_StormEater.apk
      - uses: actions/upload-artifact@v4
        with:
          name: Odogwu_StormEater.apk
          path: build/android/Odogwu_StormEater.apk
